[alias] # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release] # Modify profile settings via config.
opt-level = 3 # Optimization level.
debug = false # Include debug info.
debug-assertions = false # Enables debug assertions.
overflow-checks = false # Enables runtime integer overflow checks.
lto = "fat" # Sets link-time optimization.
panic = 'abort' # The panic strategy.
incremental = true # Incremental compilation.
